export const cardsData = [
  { title: "Title 1", description: "Hi This is Test" },
  { title: "Title 2", description: "Hi This is Test" },
  { title: "Title 3", description: "Hi This is Test" },
  { title: "Title 4", description: "Hi This is Test" },
  { title: "Title 5", description: "Hi This is Test" },
  { title: "Title 6", description: "Hi This is Test" },
  { title: "Title 7", description: "Hi This is Test" },
  { title: "Title 8", description: "Hi This is Test" },
  { title: "Title 9", description: "Hi This is Test" },
  { title: "Title 10", description: "Hi This is Test" },
  { title: "Title 11", description: "Hi This is Test" },
  { title: "Title 12", description: "Hi This is Test" },
  { title: "Title 13", description: "Hi This is Test" },
  { title: "Title 14", description: "Hi This is Test" },
  { title: "Title 15", description: "Hi This is Test" },
  { title: "Title 16", description: "Hi This is Test" },
  { title: "Title 17", description: "Hi This is Test" },
  { title: "Title 18", description: "Hi This is Test" },
  { title: "Title 19", description: "Hi This is Test" },
  { title: "Title 20", description: "Hi This is Test" },
];

export const homeTabsData = [
  { id: "1", name: "Narendra", description: "Frontend Developer" },
  { id: "2", name: "Muneera", description: "Frontend Developer" },
  { id: "3", name: "Nagendra", description: "Frontend Developer" },
  { id: "4", name: "Pavan", description: "Backend Developer" },
  { id: "5", name: "Ravi Teja", description: "Backend Developer" },
  { id: "6", name: "Lalitha", description: "Frontend Developer" },
  { id: "7", name: "Mahendra", description: "Backend Developer" },
];
